import os
os.system("cls")
# first class objects
# python functions are first class objects 
# 1. instance of object
# 2. can store functtion n variable
# 3. pass function as parameter in another function
# 4. return function from a function
# can store them in a data structure

# 1. python functions are objects 
# can be stored in variables
print("python functions are objects")
print("can be stored in variables")
def shout(text: str)->str:
    return text.upper()
yell=shout
print(yell("hello"))

# functions can be passed as arguments to other functions
print("\nfunctions can be passed as arguments to other functions")
def whisper(text):
    return text.lower()
def greet(func):
    greetings=func("text generated by a function passed as argument")
    print(greetings)
greet(shout)
greet(whisper)

# function can RETURN another function
print("\nfunction can RETURN another function")
def create_adder(x:int)->int:
    def adder(y:int)->int:
        return x+y
    # function returning anotehr function
    return adder
# driver code
add_15=create_adder(15)
print(add_15(10))